DATASET:
  DATASET_DIR: ./dataset
  TRAINING_DIR: ./dataset/train
  TESTING_DIR: ./dataset/val
  TRAINING_DATASET_LEN: 200000
  TESTING_DATASET_LEN: 5000
  CAPTCHA:
    FONT_DIR:
      - './fonts/Roboto-Black.ttf'
      - './fonts/Roboto-Light.ttf'
      - './fonts/Roboto-Regular.ttf'
      - './fonts/Roboto-Bold.ttf'
      - './fonts/Roboto-Thin.ttf'
      - './fonts/Roboto-Medium.ttf'
    IMG_HEIGHT: 22
    IMG_WIDTH: 54
    CLASS_NUM: 36
    CHAR_LEN: 4
SOLVER:
  LR: 0.0003
  BATCH_SIZE: 256
  EPOCH: 15
LOGGER:
  CHECKPOINT_DIR: ./checkpoint
  LOG_DIR: ./logs
